version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "8071:3306"  # Expose MySQL on 8071 (instead of default 3306)
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "8072:8072"  # Expose backend API on 8072
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://testuser:testpassword@db/testdb
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "8073:8073"  # Expose frontend on 8073
    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8074:8074"  # Expose Nginx proxy on 8074
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8075:8080"  # Expose Adminer on 8075
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
